In [1]:
import torch

##### Create 2d tensor

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

In [5]:
#set datatype
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32)
my_tensor.type

<function Tensor.type>

In [7]:
#set the device either gpu or cpu
#cpu default
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,
                        device="cpu")
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

###### auto gradients for backward propagationm

In [8]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype= torch.float32,
                        device="cpu",requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

###### If have cuda then run on it or cpu

In [10]:
divice = "cuda" if torch.cuda.is_available() else "cpu"

### Tensor attribute

In [11]:
#tensor type
my_tensor.dtype

torch.float32

In [13]:
#Which device, gpu or cpu? check
my_tensor.device

device(type='cpu')

In [14]:
#shape
my_tensor.shape

torch.Size([2, 3])

In [16]:
#requires gradients or not. result will be true cause I have set it as true
my_tensor.requires_grad

True

### Other common initialization method

In [24]:
#create 3x3 tensor and empty and uninitialize data. don't decived by zeros, it's not a zero matrix
x = torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
#zero tensor
x = torch.zeros((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
#3x3 matrix random value with uniform distribution.(within 0 to 1)
r = torch.rand((3,3))
r

tensor([[0.1987, 0.4720, 0.4552],
        [0.4676, 0.3386, 0.6685],
        [0.3624, 0.6775, 0.9686]])

In [27]:
# matrix of ones
o = torch.ones((3,3))
o

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
#identity matrix, diagonal
i = torch.eye(5,5)
i

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
# like a python range
a = torch.arange(start=0, end = 5, step=1)
a

tensor([0, 1, 2, 3, 4])

In [31]:
#step= 3
a = torch.arange(start=0, end = 15, step=3)
a

tensor([ 0,  3,  6,  9, 12])

In [33]:
# equally dividation
# means the number starts from 0.1 and within 0.1 and 1 there will be 10 dividation with equal space
#steps = 10 means , 10 points
l = torch.linspace(start = 0.1, end =1, steps = 10)
l

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [34]:
# initialize data and make those value normally distribute with a mean a 0 and standard daviation of 1
m = torch.empty(size=(1,5)).normal_(mean=0, std=1)
m

tensor([[ 1.5216,  0.8724, -0.3383,  0.2045, -1.7930]])

In [35]:
# uniform distribution
u = torch.empty(size=(1,5)).uniform_(0,1)
u

tensor([[0.2093, 0.9474, 0.6116, 0.7683, 0.0475]])

In [36]:
# create diagonal matrix
d = torch.diag(torch.ones(3))
d

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])