How to initialize and convert tensors to other types (int, float, double)

In [1]:
import torch

In [4]:
tensor = torch.arange(4)
tensor
#int64 default

tensor([0, 1, 2, 3])

In [3]:
#tensor shape
tensor.shape

torch.Size([4])

In [5]:
# turn it into boolian
print(tensor.bool())

tensor([False,  True,  True,  True])


In [6]:
#make it into short and print
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [7]:
#make it into long and print
print(tensor.long())

tensor([0, 1, 2, 3])


In [8]:
#make it into half and print
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [9]:
#make it into float and print
print(tensor.float())

tensor([0., 1., 2., 3.])


In [10]:
#convert
import numpy as np
np_array = np.zeros((5,5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
tensor = torch.from_numpy(np_array)

In [12]:
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [17]:
#back to numpy
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
