### Tensor Math

In [2]:
import torch 

In [3]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [4]:
#addition
# add x and y and store it on z1
z1 = torch.empty(3)
torch.add(x,y, out=z1)
z1

tensor([10., 10., 10.])

In [5]:
# another way , addition
z2 = torch.add(x,y)
z2

tensor([10, 10, 10])

In [6]:
#best way, addition
z = x + y
z

tensor([10, 10, 10])

In [8]:
# Subtraction
z = x - y
z

tensor([-8, -6, -4])

In [9]:
# Division
z = torch.true_divide(x,y)
z

tensor([0.1111, 0.2500, 0.4286])

In [19]:
# Inplace operation
# inplace means it will not create any copy!
t = torch.zeros(3)
t

tensor([0., 0., 0.])

In [21]:
t.add_(x)

tensor([2., 4., 6.])

In [23]:
#another way inplace
t +=x
t

tensor([ 4.,  8., 12.])

In [25]:
# Exponentiation
z

tensor([1, 4, 9])

In [26]:
x

tensor([1, 2, 3])

In [28]:
po = x.pow(2)
po

tensor([1, 4, 9])

In [30]:
zo = z.pow(2)
zo

tensor([ 1, 16, 81])

In [31]:
# simple compare
z = x > 0
z

tensor([True, True, True])

In [32]:
z = x < 0
z

tensor([False, False, False])

In [36]:
#matrix multiplication
x1 = torch.rand((2,5))
x1

tensor([[0.1403, 0.1045, 0.5384, 0.9508, 0.2746],
        [0.9497, 0.1213, 0.0733, 0.5248, 0.1712]])

In [37]:
x2 = torch.rand((5,3))
x2

tensor([[0.9207, 0.0343, 0.7373],
        [0.3386, 0.4263, 0.5059],
        [0.4350, 0.9273, 0.1317],
        [0.8317, 0.8385, 0.3302],
        [0.9643, 0.7950, 0.0588]])

In [38]:
#Performs a matrix multiplication of the matrices input and mat2
x3 = torch.mm(x1,x2)
x3

tensor([[1.4544, 1.5641, 0.5573],
        [1.5489, 0.7283, 0.9545]])

In [40]:
x3 = x1.mm(x2)
x3

tensor([[1.4544, 1.5641, 0.5573],
        [1.5489, 0.7283, 0.9545]])

In [34]:
# Matrix exponentiation
# make 5 x 5 random float matrix
matrix_exp = torch.rand(5,5)
matrix_exp

tensor([[0.6601, 0.1925, 0.5790, 0.7395, 0.7454],
        [0.0158, 0.0962, 0.0112, 0.7427, 0.2007],
        [0.5289, 0.8813, 0.6594, 0.3458, 0.7282],
        [0.2776, 0.0601, 0.0075, 0.0678, 0.2438],
        [0.6639, 0.1465, 0.5888, 0.5967, 0.9024]])

In [35]:
print(matrix_exp.matrix_power(3))

tensor([[3.1738, 1.7672, 2.7169, 3.2557, 4.0738],
        [0.6500, 0.2768, 0.5394, 0.6415, 0.8135],
        [3.1627, 1.7433, 2.6056, 3.2156, 4.0431],
        [0.8272, 0.4465, 0.6939, 0.7609, 1.0364],
        [3.3609, 1.8896, 2.8879, 3.4253, 4.3142]])


In [43]:
# Element wise mult
z = x * y
print(z)
print(x)
print(y)

tensor([ 9, 16, 21])
tensor([1, 2, 3])
tensor([9, 8, 7])


In [44]:
# Dot product
z = torch.dot(x,y)
print(z)

tensor(46)


In [45]:
# Batch matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor1

tensor([[[0.4597, 0.6889, 0.4073,  ..., 0.6403, 0.1476, 0.1289],
         [0.9295, 0.7741, 0.7017,  ..., 0.4799, 0.3264, 0.0430],
         [0.8660, 0.3209, 0.5083,  ..., 0.4510, 0.0412, 0.8592],
         ...,
         [0.2455, 0.6475, 0.8345,  ..., 0.3056, 0.5486, 0.8102],
         [0.4285, 0.1107, 0.6134,  ..., 0.9856, 0.1010, 0.9020],
         [0.1177, 0.4934, 0.2163,  ..., 0.8965, 0.2325, 0.0451]],

        [[0.8655, 0.6312, 0.6385,  ..., 0.4922, 0.3903, 0.1546],
         [0.0573, 0.1215, 0.4475,  ..., 0.7570, 0.4967, 0.1092],
         [0.8074, 0.4648, 0.2503,  ..., 0.6143, 0.0344, 0.4445],
         ...,
         [0.8867, 0.1519, 0.8007,  ..., 0.0743, 0.8028, 0.8593],
         [0.1464, 0.6478, 0.1071,  ..., 0.7094, 0.2596, 0.6864],
         [0.4326, 0.8296, 0.5172,  ..., 0.5523, 0.4868, 0.8482]],

        [[0.1815, 0.1864, 0.5119,  ..., 0.1664, 0.7593, 0.2546],
         [0.4924, 0.2325, 0.8021,  ..., 0.9981, 0.9235, 0.6625],
         [0.0646, 0.4593, 0.0670,  ..., 0.7486, 0.6447, 0.

In [46]:
tensor2 = torch.rand((batch, m, p))
tensor2

tensor([[[0.8689, 0.1102, 0.1797,  ..., 0.3852, 0.5542, 0.7662],
         [0.3922, 0.8138, 0.2887,  ..., 0.8374, 0.3890, 0.3193],
         [0.0240, 0.5369, 0.9912,  ..., 0.9583, 0.5920, 0.1645],
         ...,
         [0.2284, 0.1150, 0.7116,  ..., 0.1233, 0.1121, 0.0567],
         [0.6494, 0.2359, 0.6633,  ..., 0.5776, 0.2509, 0.2999],
         [0.7888, 0.8365, 0.0819,  ..., 0.4233, 0.2128, 0.1725]],

        [[0.8881, 0.9576, 0.1707,  ..., 0.1894, 0.0840, 0.6206],
         [0.9804, 0.2596, 0.9771,  ..., 0.4526, 0.4760, 0.9248],
         [0.5487, 0.3863, 0.3875,  ..., 0.9927, 0.6377, 0.7272],
         ...,
         [0.5586, 0.3661, 0.8753,  ..., 0.2669, 0.1118, 0.9478],
         [0.1791, 0.0620, 0.6704,  ..., 0.6760, 0.8219, 0.6423],
         [0.4911, 0.1432, 0.2136,  ..., 0.8053, 0.9533, 0.8965]],

        [[0.0211, 0.0050, 0.2912,  ..., 0.3580, 0.2750, 0.8125],
         [0.8252, 0.7794, 0.6005,  ..., 0.5110, 0.8955, 0.5166],
         [0.6415, 0.1279, 0.1399,  ..., 0.7398, 0.2558, 0.

In [48]:
out_bmm = torch.bmm(tensor1, tensor2)
out_bmm

tensor([[[5.5338, 4.6033, 5.4288,  ..., 4.4271, 5.6786, 4.5356],
         [5.2713, 4.7512, 4.9943,  ..., 4.7425, 6.1504, 3.8108],
         [5.0973, 4.5325, 4.3851,  ..., 4.1837, 5.2239, 3.9418],
         ...,
         [4.9554, 5.0567, 5.2347,  ..., 5.0456, 5.1668, 4.1722],
         [4.6990, 4.6940, 5.1702,  ..., 3.9500, 5.0574, 4.2102],
         [3.4546, 3.5182, 3.4877,  ..., 3.0746, 3.5139, 2.6796]],

        [[6.7769, 5.7204, 6.3230,  ..., 6.2919, 6.4010, 6.9872],
         [4.3289, 3.1418, 3.8013,  ..., 4.0699, 3.9687, 4.5886],
         [5.9473, 4.1763, 3.9355,  ..., 3.7820, 4.2390, 5.4616],
         ...,
         [5.4114, 4.1433, 4.9975,  ..., 5.4912, 5.1413, 5.7657],
         [5.3281, 3.7677, 4.0897,  ..., 4.9550, 4.6350, 5.4215],
         [4.4577, 2.5944, 4.4219,  ..., 4.0299, 2.8928, 4.2071]],

        [[3.7492, 5.0061, 2.1559,  ..., 3.7808, 3.7182, 2.7924],
         [5.1933, 5.4178, 3.3475,  ..., 4.4882, 3.6250, 4.0575],
         [4.4464, 5.6154, 2.5086,  ..., 4.1635, 3.6704, 4.

# Need to know more about this BMM (batch matrix multiplication)